ROUTE_DATABASE = 'metadata'

ROUTE_PREFIX = "/filer"
ROUTE_NAME = "FILER Functional Genomics Repository"
ROUTE_ABBREVIATION = "FILER"
ROUTE_DESCRIPTION = {}
ROUTE_TAGS = [f'{ROUTE_NAME}']

TRACKS_PER_API_REQUEST_LIMIT = 50

FILER_HTTP_CLIENT_TIMEOUT=60
CACHEDB_PARALLEL_TIMEOUT=30
